// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ5JEgRaTGEwBsorrtm8DjwDnmzCIFUqY',
    appId: '1:463349550398:web:83e9096e441b0a3d43306f',
    messagingSenderId: '463349550398',
    projectId: 'piyawat-d038f',
    authDomain: 'piyawat-d038f.firebaseapp.com',
    storageBucket: 'piyawat-d038f.firebasestorage.app',
    measurementId: 'G-2L9Y83FH1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvVoTKjoNu7VaMrdRuYttPYAlQCCrdi9Y',
    appId: '1:463349550398:android:f3df31e88acf98f443306f',
    messagingSenderId: '463349550398',
    projectId: 'piyawat-d038f',
    storageBucket: 'piyawat-d038f.firebasestorage.app',
  );
}
